version: '3.7'

services:
  nats:
    image: nats-streaming:latest
    command: -cid test-cluster -m 8222 --store SQL --sql_driver postgres --sql_source postgresql://default:password@db:5432/nss_db?sslmode=disable -SD # -DV
    entrypoint: /nats-streaming-server
    ports:
      - "4222:4222"
      - "8222:8222"
    depends_on:
      - db

  envoy:
    image: envoyproxy/envoy:latest
    restart: always
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    network_mode: "host"

  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./postgres/data
        target: /var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080